; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
  ESP32async/ESPAsyncWebServer @ ^3.7.9
	powerbroker2/SafeString@^4.1.35
  adafruit/Adafruit SSD1306 @ ^2.5.15
	adafruit/Adafruit GFX Library @ ^1.11.11
	aki237/Adafruit_ESP32_SH1106@^1.0.2
	ricmoo/QRCode@^0.0.1
  adafruit/Adafruit ADS1X15 @ ^2.6.0
  sstaub/MCP_23017 @ ^1.0.0
# board_build.filesystem = LittleFS
monitor_speed = 115200
monitor_filters = 
	colorize
	send_on_enter
monitor_eol = CR
monitor_echo = yes
board_build.filesystem = spiffs

[env:wemos_d1_mini32]
build_type = release
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = 
	ESP32async/AsyncTCP @ ^3.4.9
	${env.lib_deps}
monitor_filters = 
  ${env.monitor_filters}

[env:wemos_d1_mini32debug]
build_type = debug
platform = espressif32
board = wemos_d1_mini32
framework = arduino
build_flags = 
	-DDEBUGPORT=0
lib_deps = 
	ESP32async/AsyncTCP @ ^3.4.9
	${env.lib_deps}
monitor_filters = 
	esp32_exception_decoder
  ${env.monitor_filters}

[env:D1_MINI8266]
build_type = release
platform = espressif8266
board = d1_mini
lib_deps = 
  ESP32async/ESPAsyncTCP @ ^2.0.0
	${env.lib_deps}
monitor_filters = 
  ${env.monitor_filters}

[env:D1_MINI8266_DEBUG]
build_type = debug  
platform = espressif8266
board = d1_mini
lib_deps = 
  ESP32async/ESPAsyncTCP @ ^2.0.0
	${env.lib_deps}
build_flags = 
	-DDEBUGPORT=0
monitor_filters = 
  esp8266_exception_decoder
  ${env.monitor_filters}
