; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif8266
framework = arduino
lib_deps = 
	esphome/ESPAsyncWebServer-esphome @ ^3.3.0
  me-no-dev/ESPAsyncTCP@^1.2.2
	powerbroker2/SafeString@^4.1.35
	adafruit/Adafruit GFX Library @ ^1.11.11
	aki237/Adafruit_ESP32_SH1106@^1.0.2
	# adafruit/Adafruit SSD1306 @ ^2.5.13
	ricmoo/QRCode@^0.0.1
	# bblanchon/ArduinoJson@^7.2.1
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_filters = 
	esp8266_exception_decoder
	colorize
	send_on_enter
monitor_eol = CR
monitor_echo = yes

[env:D1_MINI]
build_type = release
board = d1_mini

[env:D1_MINI_DEBUG]
build_type = debug
board = d1_mini
build_flags = 
  -DDEBUG